### ISSUE TITLE
Properly handle unknown dependencies

### ISSUE THREAD

**Issue by alvarocavalcanti** [alvarocavalcanti/pierre-decheck#28]
Currently, Pierre does not handle unknown dependencies.

**Comment by alvarocavalcanti** [comment]
As can be seen here https://github.com/alvarocavalcanti/pierre-decheck/pull/24 it does not display any dependency check at all.

**Comment by mosheeshel** [comment]
What's the desired behavior?

**Comment by alvarocavalcanti** [comment]
I don't know. Do you have a suggestion?

Maybe it should fail the check, because if it cannot guarantee the dependency is satisfied, than it isn't. But instead of having it marked as `open` we could have a new status, `unknown`. That way the user can act upon it (delete, edit, etc). What do you think?

**Comment by mosheeshel** [comment]
I think it is not a good idea to fail a check simply because the words "depends on" appear in it... dependency should be actionable - in GitHub context this is 
Merged, Closed, Deleted (on PRs, Issues) and other statuses I can't just think of yet.

If there is something else (hypothetically, not suggesting we support this) like a task in Jira, that also has clear statuses - but I don't think we should venture (yet?) beyond github. A non existent/accessible repo (like happened to me), should put a notice in the log maybe, but not do anything until we specify the behavior (someone maybe would open an issue?)

**Comment by mosheeshel** [comment]
So for now I say - if something is unknown - log and skip - do not fail the check
